### PR TITLE
Fixed PhpDoc

### PR DESCRIPTION
**Pull request by alexmanno**
According to issue https://github.com/starekrow/lockbox/issues/7, I've fixed PhpDoc for better compatibility with fig-standards

### CODE REVIEW

**Comment by starekrow** [comment]
Looks good in principle, but the whitespace changes leaked all over the code. Can you resubmit with just the comments changed?

**Comment by KJLJon** [comment]
here is what this looks like after psr-2 is adopoted (#14)
https://github.com/KJLJon/lockbox/commit/601fe28bc547ce3cf0ef1509031d4f8f3e42ebec

**Comment by alexmanno** [comment]
@KJLJon LGTM! I think we can merge PSR-2 rules + Fixed PhpDoc together
@starekrow do you approve?

**Comment by starekrow** [comment]
Yep, I'd be happy to take a PR for both. Right now I'm getting a slightly cleaner merge by starting with #8 than #14 but there's a lot of bits to fixup by hand; I'll hold off for now. Definitely want to do a change like this (touching every source line) sooner than later.

**Comment by KJLJon** [comment]
KJLJon/lockbox@601fe28 merges #8 and #14 together from the 2 separate timelines / branches.
I will submit a PR for that and if approved it should automatically close both #14 and #8 since it is pulled from both of their histories.

**Pull request merged**
